/**
 * Icon registry for the catalog.
 *
 * Catalog entries name their icon as a string (`icon: 'Filter'`) so the catalog
 * stays free of React imports. This module is the only place that turns those
 * names back into components. The import list is explicit — a dynamic
 * `lucide-react/dist/esm/icons/${name}` import would defeat tree-shaking and ship
 * the whole icon set.
 */

import {
  ArrowUpDown,
  Bookmark,
  Box,
  Braces,
  Bug,
  CircleAlert,
  CirclePlus,
  CircleSlash,
  Clock,
  Columns3,
  Combine,
  Copy,
  Database,
  Download,
  Droplet,
  Eye,
  EyeOff,
  FileCode2,
  FileJson,
  FileSpreadsheet,
  FileSymlink,
  FileText,
  Filter,
  Fingerprint,
  Flag,
  GitMerge,
  Hash,
  Layers,
  LayoutTemplate,
  ListChecks,
  Mountain,
  OctagonX,
  PenLine,
  Play,
  Plus,
  Radio,
  Regex,
  Ruler,
  Search,
  ShieldCheck,
  Sigma,
  Sparkles,
  StickyNote,
  Table2,
  Terminal,
  Trash2,
  TriangleAlert,
  Type,
  Upload,
  Variable,
  Workflow,
  type LucideIcon,
} from 'lucide-react'

/** Every icon name a catalog entry (or the canvas chrome) may reference. */
const ICONS: Record<string, LucideIcon> = {
  ArrowUpDown,
  Bookmark,
  Box,
  Braces,
  Bug,
  CircleAlert,
  CirclePlus,
  CircleSlash,
  Clock,
  Columns3,
  Combine,
  Copy,
  Database,
  Download,
  Droplet,
  Eye,
  EyeOff,
  FileCode2,
  FileJson,
  FileSpreadsheet,
  FileSymlink,
  FileText,
  Filter,
  Fingerprint,
  Flag,
  GitMerge,
  Hash,
  Layers,
  LayoutTemplate,
  ListChecks,
  Mountain,
  OctagonX,
  PenLine,
  Play,
  Plus,
  Radio,
  Regex,
  Ruler,
  Search,
  ShieldCheck,
  Sigma,
  Sparkles,
  StickyNote,
  Table2,
  Terminal,
  Trash2,
  TriangleAlert,
  Type,
  Upload,
  Variable,
  Workflow,
}

/** Resolves a catalog icon name. Unknown names fall back to a neutral box. */
export function catalogIcon(name: string): LucideIcon {
  return ICONS[name] ?? Box
}
