/**
 * Client for the runnable JSON files in the library (`/workspace/files`).
 *
 * A Pipeline stage normally runs a Job the Studio owns. This is the other way
 * in: point a stage at a `.json` that already exists — generated by another
 * team, versioned in another repository, written by hand — and run it as it
 * stands.
 *
 * Nothing is imported and nothing is cached. The file is the source: the runner
 * reads it at the moment the stage starts, so an edit made outside the Studio
 * takes effect on the next run. The Studio only reads it to show and lint what
 * would run, and it never writes it back.
 *
 * Every path here is **relative to the library root**, forward slashes. An
 * absolute one names a directory that exists on one machine, and a Pipeline that
 * runs on its author's laptop and silently stops running anywhere else is worse
 * than one that never ran.
 */

import type { PipelineSpec } from '@/types/pipeline'

import {
  authHeaders,
  DEFAULT_RUNNER_URL,
  RunnerError,
  RUNNER_UNREACHABLE_MESSAGE,
} from './client'

/** One runnable JSON in the library, as the runner lists it. */
export interface LibraryFile {
  /** Relative to the library root, forward slashes. */
  path: string
  /** File name without the extension — what to show when there is no better name. */
  name: string
  size: number
  /** Last modification, epoch **seconds** (the runner reports `st_mtime`). */
  modified: number
}

export interface LibraryListing {
  /** Absolute path of the library root, so the interface can say where this is. */
  root: string
  files: LibraryFile[]
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

function asString(value: unknown, fallback = ''): string {
  return typeof value === 'string' ? value : fallback
}

function asNumber(value: unknown): number {
  return typeof value === 'number' && Number.isFinite(value) ? value : 0
}

function normalizeBaseUrl(baseUrl: string): string {
  return baseUrl.replace(/\/+$/, '')
}

async function readErrorMessage(response: Response): Promise<string> {
  let body = ''
  try {
    body = await response.text()
  } catch {
    body = ''
  }
  try {
    const parsed: unknown = JSON.parse(body)
    if (isRecord(parsed) && typeof parsed.detail === 'string' && parsed.detail.length > 0) {
      return parsed.detail
    }
  } catch {
    /* not JSON — fall through to the status line */
  }
  return `Local runner error (HTTP ${response.status})`
}

async function get(
  baseUrl: string,
  path: string,
  token?: string,
  signal?: AbortSignal,
): Promise<unknown> {
  let response: Response
  try {
    response = await fetch(`${normalizeBaseUrl(baseUrl)}${path}`, {
      method: 'GET',
      headers: { 'Content-Type': 'application/json', ...authHeaders(token) },
      signal,
    })
  } catch (error) {
    if (error instanceof DOMException && error.name === 'AbortError') throw error
    throw new RunnerError(RUNNER_UNREACHABLE_MESSAGE, 'unreachable', undefined, error)
  }
  if (!response.ok) {
    throw new RunnerError(await readErrorMessage(response), 'http', response.status)
  }
  try {
    return await response.json()
  } catch (error) {
    throw new RunnerError(
      'The local runner returned a malformed response.',
      'malformed',
      response.status,
      error,
    )
  }
}

function toFile(value: unknown): LibraryFile | null {
  if (!isRecord(value)) return null
  const path = asString(value.path)
  if (!path) return null
  return {
    path,
    name: asString(value.name, path),
    size: asNumber(value.size),
    modified: asNumber(value.modified),
  }
}

/** Every runnable JSON in the library. Needs `workspace:Read`. */
export async function listLibraryFiles(
  baseUrl: string = DEFAULT_RUNNER_URL,
  token?: string,
  signal?: AbortSignal,
): Promise<LibraryListing> {
  const payload = await get(baseUrl, '/workspace/files', token, signal)
  const record = isRecord(payload) ? payload : {}
  const files = Array.isArray(record.files) ? record.files : []
  return {
    root: asString(record.root),
    // A row the runner sent in a shape this build does not understand is dropped
    // rather than shown as a file with no path, which would be unrunnable anyway.
    files: files.map(toFile).filter((file): file is LibraryFile => file !== null),
  }
}

/**
 * The JSON at a library path, exactly as it is on disk — uncompiled.
 *
 * Read to show and lint what a stage would run. It is deliberately re-read
 * rather than remembered: what is on screen has to be what the next run
 * executes.
 */
export async function readLibraryFile(
  baseUrl: string = DEFAULT_RUNNER_URL,
  path: string,
  token?: string,
  signal?: AbortSignal,
): Promise<PipelineSpec> {
  const encoded = path
    .split('/')
    .filter(Boolean)
    .map((part) => encodeURIComponent(part))
    .join('/')
  const payload = await get(baseUrl, `/workspace/files/${encoded}`, token, signal)
  const record = isRecord(payload) ? payload : {}
  if (!isRecord(record.pipeline)) {
    throw new RunnerError(
      `The local runner returned no pipeline for ${path}.`,
      'malformed',
      200,
    )
  }
  return record.pipeline as unknown as PipelineSpec
}
